################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SAG_SRCS += \

SAG_FILE += \

GPROF_OUT := 
PWR_OUT := 
SIZE_OUTPUTS := 
READELF_OUTPUTS := 
EXECUTABLES := 
OBJDUMP_OUTPUTS := 
OBJS := 
SYMBOL_OUTPUTS := 
S_UPPER_DEPS := 
GCOV_OUT := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
3rd-party/freertos-V5 \
3rd-party/freertos-V5/portable/GCC/RISC-V \
3rd-party/freertos-V5/portable/MemMang \
application/app \
application/audio \
application/keyboard \
application/print \
application/usbstd \
boot/B91 \
common \
common/usb_dbg \
drivers/B91 \
drivers/B91/ext_driver \
drivers/B91/flash \
proj/common \
vendor/UI/components \
vendor/UI/images \
vendor/UI/screens \
vendor/UI \
vendor/common \
vendor/common/chip_adapt_layer \
vendor/common/mi_api \
vendor/common/mi_api/libs \
vendor/common/mi_api/libs/third_party/micro-ecc \
vendor/common/mi_api/mi_vendor \
vendor/common/mi_api/mijia_ble_api \
vendor/common/nl_api \
vendor/lvgl/demos/benchmark/assets \
vendor/lvgl/demos/benchmark \
vendor/lvgl/demos/keypad_encoder \
vendor/lvgl/demos/music/assets \
vendor/lvgl/demos/music \
vendor/lvgl/demos/stress \
vendor/lvgl/demos/widgets/assets \
vendor/lvgl/demos/widgets \
vendor/lvgl/env_support/rt-thread \
vendor/lvgl/env_support/rt-thread/squareline \
vendor/lvgl/examples/anim \
vendor/lvgl/examples/assets \
vendor/lvgl/examples/assets/emoji \
vendor/lvgl/examples/event \
vendor/lvgl/examples/get_started \
vendor/lvgl/examples/layouts/flex \
vendor/lvgl/examples/layouts/grid \
vendor/lvgl/examples/libs/bmp \
vendor/lvgl/examples/libs/ffmpeg \
vendor/lvgl/examples/libs/freetype \
vendor/lvgl/examples/libs/gif \
vendor/lvgl/examples/libs/png \
vendor/lvgl/examples/libs/qrcode \
vendor/lvgl/examples/libs/rlottie \
vendor/lvgl/examples/libs/sjpg \
vendor/lvgl/examples/others/fragment \
vendor/lvgl/examples/others/gridnav \
vendor/lvgl/examples/others/ime \
vendor/lvgl/examples/others/imgfont \
vendor/lvgl/examples/others/monkey \
vendor/lvgl/examples/others/msg \
vendor/lvgl/examples/others/snapshot \
vendor/lvgl/examples/porting \
vendor/lvgl/examples/scroll \
vendor/lvgl/examples/styles \
vendor/lvgl/examples/widgets/animimg \
vendor/lvgl/examples/widgets/arc \
vendor/lvgl/examples/widgets/bar \
vendor/lvgl/examples/widgets/btn \
vendor/lvgl/examples/widgets/btnmatrix \
vendor/lvgl/examples/widgets/calendar \
vendor/lvgl/examples/widgets/canvas \
vendor/lvgl/examples/widgets/chart \
vendor/lvgl/examples/widgets/checkbox \
vendor/lvgl/examples/widgets/colorwheel \
vendor/lvgl/examples/widgets/dropdown \
vendor/lvgl/examples/widgets/img \
vendor/lvgl/examples/widgets/imgbtn \
vendor/lvgl/examples/widgets/keyboard \
vendor/lvgl/examples/widgets/label \
vendor/lvgl/examples/widgets/led \
vendor/lvgl/examples/widgets/line \
vendor/lvgl/examples/widgets/list \
vendor/lvgl/examples/widgets/menu \
vendor/lvgl/examples/widgets/meter \
vendor/lvgl/examples/widgets/msgbox \
vendor/lvgl/examples/widgets/obj \
vendor/lvgl/examples/widgets/roller \
vendor/lvgl/examples/widgets/slider \
vendor/lvgl/examples/widgets/span \
vendor/lvgl/examples/widgets/spinbox \
vendor/lvgl/examples/widgets/spinner \
vendor/lvgl/examples/widgets/switch \
vendor/lvgl/examples/widgets/table \
vendor/lvgl/examples/widgets/tabview \
vendor/lvgl/examples/widgets/textarea \
vendor/lvgl/examples/widgets/tileview \
vendor/lvgl/examples/widgets/win \
vendor/lvgl/src/core \
vendor/lvgl/src/draw/arm2d \
vendor/lvgl/src/draw \
vendor/lvgl/src/draw/nxp/pxp \
vendor/lvgl/src/draw/nxp/vglite \
vendor/lvgl/src/draw/renesas \
vendor/lvgl/src/draw/sdl \
vendor/lvgl/src/draw/stm32_dma2d \
vendor/lvgl/src/draw/sw \
vendor/lvgl/src/draw/swm341_dma2d \
vendor/lvgl/src/extra/layouts/flex \
vendor/lvgl/src/extra/layouts/grid \
vendor/lvgl/src/extra/libs/bmp \
vendor/lvgl/src/extra/libs/ffmpeg \
vendor/lvgl/src/extra/libs/freetype \
vendor/lvgl/src/extra/libs/fsdrv \
vendor/lvgl/src/extra/libs/gif \
vendor/lvgl/src/extra/libs/png \
vendor/lvgl/src/extra/libs/qrcode \
vendor/lvgl/src/extra/libs/rlottie \
vendor/lvgl/src/extra/libs/sjpg \
vendor/lvgl/src/extra/libs/tiny_ttf \
vendor/lvgl/src/extra \
vendor/lvgl/src/extra/others/fragment \
vendor/lvgl/src/extra/others/gridnav \
vendor/lvgl/src/extra/others/ime \
vendor/lvgl/src/extra/others/imgfont \
vendor/lvgl/src/extra/others/monkey \
vendor/lvgl/src/extra/others/msg \
vendor/lvgl/src/extra/others/snapshot \
vendor/lvgl/src/extra/themes/basic \
vendor/lvgl/src/extra/themes/default \
vendor/lvgl/src/extra/themes/mono \
vendor/lvgl/src/extra/widgets/animimg \
vendor/lvgl/src/extra/widgets/calendar \
vendor/lvgl/src/extra/widgets/chart \
vendor/lvgl/src/extra/widgets/colorwheel \
vendor/lvgl/src/extra/widgets/imgbtn \
vendor/lvgl/src/extra/widgets/keyboard \
vendor/lvgl/src/extra/widgets/led \
vendor/lvgl/src/extra/widgets/list \
vendor/lvgl/src/extra/widgets/menu \
vendor/lvgl/src/extra/widgets/meter \
vendor/lvgl/src/extra/widgets/msgbox \
vendor/lvgl/src/extra/widgets/span \
vendor/lvgl/src/extra/widgets/spinbox \
vendor/lvgl/src/extra/widgets/spinner \
vendor/lvgl/src/extra/widgets/tabview \
vendor/lvgl/src/extra/widgets/tileview \
vendor/lvgl/src/extra/widgets/win \
vendor/lvgl/src/font \
vendor/lvgl/src/hal \
vendor/lvgl/src/misc \
vendor/lvgl/src/widgets \
vendor/lvgl/tests/makefile \
vendor/lvgl/tests/src \
vendor/lvgl/tests/src/test_cases \
vendor/lvgl/tests/src/test_fonts \
vendor/lvgl/tests/unity \
vendor/mesh \
vendor/tuong \
vendor/user_app \

